name: edge_to_edge_system_ui
description: Flutter plugin providing an opinionated Edge-to-Edge system UI controller with a Kotlin implementation for Android.
version: 0.1.0-dev.4
homepage: https://pub.dev/documentation/edge_to_edge_system_ui/latest/
repository: https://github.com/otabekoff/edge_to_edge_system_ui
environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=2.10.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.example.edge_to_edge_system_ui
        pluginClass: EdgeToEdgeSystemUiPlugin
      ios:
        pluginClass: EdgeToEdgeSystemUiPlugin

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0